// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjvrrngouzcrrgjccbod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqdnJybmdvdXpjcnJnamNjYm9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwOTA3MTUsImV4cCI6MjA2MzY2NjcxNX0.bLZdIv0qrH6gN9p-cvDKg55NKynGKFDXhNrbvPVoy_I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);